# 测试项目
[project]
name = 'test_project'

# 测试报告
[report]
title = "自动化测试报告"
tester_name = '123'

# mysql 数据库
[mysql]
host = '127.0.0.1'
port = 3306
user = 'root'
password = '123456'
database = 'test'
charset = 'utf8mb4'

# redis 数据库
[redis]
host = '127.0.0.1'
port = 6379
password = ''
database = 0
timeout = 10

# 邮件
[email]
host = 'smtp.qq.com'
port = 465
user = '12345678@qq.com'
password = '12345678'
receiver = '87654321@qq.com'  # if more, use: [str]
ssl = true
send = false

# 钉钉
[ding]
webhook = ''
proxies.http = ''
proxies.https = ''
send = false

# 飞书
[lark]
webhook = ''
proxies.http = ''
proxies.https = ''
send = false


# 请求发送
[request]
timeout = 10
verify = false
redirects = true
proxies.http = ''
proxies.https = ''
retry = 3
